# Generated by Django 2.0.3 on 2018-04-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180428_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date'], 'permissions': (('can_manipulate', 'Create/Delete blog'),)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date'], 'permissions': (('can_comment', 'Comment blog'),)},
        ),
    ]
